#server:
#  port: 9090
#eureka:
#  instance:
#    hostname: localhost
#    # 以IP地址注册到服务中心，相互注册使用IP地址
#    #prefer-ip-address: true
#  client:
#    #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设置为false。
#    #如果这是客户端的话那就默认true即可
#    register-with-eureka: false
#    #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，
#    #不需要同步其他的Eureka Server节点的数据，故而设置为false。
#    fetch-registry: false
#    service-url:
#      #设置eureka需要用户名和密码登录，其他服务都是一样
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      #http://xiao:xiao@${eureka.instance.hostname}:${server.port}/eureka/
#spring:
#  application:
#    name: eureka-server

# 端口
server:
  port: 9090

# 应用名称
spring:
  application:
    name: eureka-server

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    # 是否向注册中心注册自己
    registerWithEureka: false
    # 是否向注册中心获取注册信息
    fetchRegistry: false
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

