server:
  port: 9190

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xzg85586537/springcloud.git
          username: xzg85586537
          password: xiao136325220
          search-paths: /sc-config   # git仓库地址下的相对地址，可以配置多个，用,分割。

